ride: ride.cpp
	g++ ride.cpp -o ride

gift1: gift1.cpp
	g++ gift1.cpp -o gift1

friday: friday.cpp
	g++ friday.cpp -o friday

beads: beads.cpp
	g++ beads.cpp -o beads

milk2: milk2.cpp
	g++ milk2.cpp -o milk2

transform: transform.cpp
	g++ transform.cpp -o transform

namenum: namenum.cpp
	g++ namenum.cpp -o namenum

palsquare: palsquare.cpp
	g++ palsquare.cpp -o palsquare

dualpal: dualpal.cpp
	g++ dualpal.cpp -o dualpal

barn1: barn1.cpp
	g++ barn1.cpp -o barn1

numtri: numtri.cpp
	g++ numtri.cpp -o numtri

clean:
	rm -rf *.in *.out
